version: "3.8"  # Using a supported version (3.8 is the latest stable)

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hamaarou/data/mariadb   # Adjust the path as needed
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hamaarou/data/mariadb   # Adjust the path as needed

networks:
  inception:
    driver: bridge  # Creates a virtual network

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb  # Adjust the path if necessary
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"