version: "3.8"  #(3.8 is the latest stable)
services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_net
    expose:
      - 3306

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    ports:
      - 443:443

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    expose:
      - 9000
volumes:
  wordpress:
      name: wordpress
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/hamaarou/data/wordpress/
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hamaarou/data/mariadb/

networks:
  inception_net:
    driver: bridge